### ISSUE TITLE
LogManager: Support format strings for user and debug exceptions

### ISSUE THREAD

**Issue by BCSol** [sosy-lab/java-common-lib#12]
Instead of using a simple string message in logDebugException/logUserException,
a formatstring with Object... args would be quite convenient.
This could easily be archived by overloading the method.

There could also be a benefit in perforamance if these string only get built if acutally logged. (see logf)

**Comment by PhilippWendler** [comment]
I agree, but it is not immediately obvious how the method should look like.

Should we make it `logUserException(Level, Throwable, Object...)` like the `log` method, where the arguments are simply concatenated with ` ` as separator? Or give it a proper format string?
Or have both variants like for `log`/`logf`?

And the second question is, what should we do with the message of the throwable? `logUserException` appends them to the log message. Should we do the same or should we expect the user to add the throwable's message in the desired place on their own?

**Comment by BCSol** [comment]
My intend was a proper format string, but the the string concatenation method sounds also quite useful.
Proposal:
- Extend `@Nullable String additionalMessage` with `Object... args` which will lazily be concatenated with `" "` and appended
- Introduce `logfUserException(Level, Throwable, String, Object...`). Similary for `logDebugException` and `logException`

Regarding the the message of the throwable, we should keep the behavior of `logUserException`.
This will keep the logfile in a more uniform style.
