### ISSUE TITLE
Make Configuration serializable

### ISSUE THREAD

**Issue by kfriedberger** [sosy-lab/java-common-lib#18]
As Configuration is just a map of Strings, it should be possible to serialize it.

**Comment by PhilippWendler** [comment]
Is there a concrete use case where this is useful?
One can always dump a `Configuration` instance in the standard text format, which has the advantage that it is human-readable and backwards-compatible.

**Comment by kfriedberger** [comment]
This issue was created in the context of a cluster-based analysis in CPAchecker, which was - until now - not yet implemented in such a way and the serialization was not yet needed.
I see the configuration as a basic component for building larger components in CPAchecker, mostly operator (state-less) classes. Of course, the way via String-based serialization exists, but requires special handling in all serializable classes referencing a configuration. Thus serialization would be nice to have. It can be done directly in the configuration class, and also in backwards-compatible.

**Comment by PhilippWendler** [comment]
`Configuration` actually contains lots of fields for which serialization does not make sense or would be non-obvious no matter how we implement it:
- logger
- properties that are unused so far
- used and deprecated properties
- `PrintStream` for logging used properties
- the `TypeConverter`s (these can also happen to be non-serializable)
- the origin file (where it was declared) for each option, which is used to handle options with relative paths (would it make sense for a different process to use the same file origins here?)

If we provide a serialization implementation in the library, we need to discuss each of these items and find a solution, and users will attempt to use it even if does not suit their use case. By not providing serialization, we force users to think about these issues themselves, which is less error-prone. And I doubt we would make the best choice at first try if we have no experience with any use cases before, and then we would probably have compatibility issues.

So I suggest we do not do this for now and can reconsider once we have use cases and actual experience with what is useful for serializing `Configuration` instances.
