### ISSUE TITLE
sosy_lab.common.io.TempFile.TempFileBuilder.prefix changes the suffix, too

### ISSUE THREAD

**Issue by KlaraCimbalnik** [sosy-lab/java-common-lib#37]
In my opinion, [this line](https://github.com/sosy-lab/java-common-lib/blob/master/src/org/sosy_lab/common/io/TempFile.java#L64) is a bug.

**Comment by PhilippWendler** [comment]
Thanks! You are fully correct, and I fixed it.

It was not detected before, because in CPAchecker all but one caller do `.prefix(...).suffix(...)`.

Do you need a new snapshot of the library soon? Otherwise I would wait until another reason for a release appears.

**Comment by KlaraCimbalnik** [comment]
No thanks, not at the moment
