### ISSUE TITLE
Fix the javadoc8 build

### ISSUE THREAD

**Issue by cheshire** [sosy-lab/java-common-lib#7]
Javadoc8 includes a very strict linter.
Furthermore, this linter marks everything it doesn't like as an _error_, and refuses to build a javadoc altogether.
While I generally like linters, I think this particular one is just obnoxious (no, I don't want to specify `@return` if I think it's self-evident from the function name).
I would propose just disabling that linter, it's a single option in the ant target.

@PhilippWendler any counter-proposals?

**Comment by PhilippWendler** [comment]
We should not disable the linter altogether, but we can disable the errors for missing tags. The remaining errors should be fixed.
